config/routes.rb
TISRuby::Application.routes.draw do
  resource :products do
    collection do
      get :increase_price
      get :search
    end
  end

  root :to => "products#index"
  match ':controller(/:action(/:id))(.:format)'
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 300 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  has_many :product_attachments, dependent: :destroy
  accepts_nested_attributes_for :product_attachments, allow_destroy: true
  after_save ThinkingSphinx::RealTime.callback_for(:product)
  after_destroy ThinkingSphinx::RealTime.callback_for(:product)
end

app/models/product_attachment.rb
class ProductAttachment < ActiveRecord::Base
  belongs_to :product
  has_attached_file :photo,
                    styles: { original: ['600x400>', :png] }, convert_options: { original: '-quality 90' }
  validates_attachment :photo, presence: true,
                       content_type: { content_type: ['image/jpeg', 'image/png', 'image/gif'] },
                       size: { in: 0..2048.kilobytes }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id].to_i)
  end

  def new
    @product = Product.new
    3.times { @product.product_attachments.build }
  end

  def create
    product = Product.new(params[:product])

    if product.save
      flash[:success] = 'Product was created'
      redirect_to action: :show, id: product.id
    else
      flash[:error] = 'Product was not created due to validation failed.'
      redirect_to action: :new
    end
  end

  def search
    @products = Product.search(params[:search_query_string])
  end

  def edit
    @product = Product.find(params[:id].to_i)
    (3 - @product.product_attachments.count).times { @product.product_attachments.build }
  end

  def update
    product = Product.find(params[:product][:id].to_i)

    if product.update_attributes(params[:product])
      flash[:success] = 'Product was updated'
      redirect_to action: :show, id: product.id
    else
      flash[:error] = 'Product was not updated'
      redirect_to action: :edit, id: product.id
    end
  end

  def destroy
    if Product.destroy(params[:id])
      flash[:success] = 'Product was deleted successfully'
    else
      flash[:error] = 'Product was not deleted'
    end

    redirect_to action: :index
  end

  def increase_price
    Resque.enqueue(UpdateProductPriceBeforeTwoHundred)
    Resque.enqueue(UpdateProductPriceAfterTwoHundred)

    redirect_to action: :index
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TISRuby</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="container menu">
    <p class="menu-title">Menu: </p><nav><%= link_to 'All products', root_path %><%= link_to 'Add new product', new_products_path %></nav>
    <%= render 'shared/search' %>
  </div>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/product/show.html.haml
%h1= @product.name

.product-details
  .details-block
    %p.label= 'Price: '
    %p.data= '$'+@product.price.to_s
  .details-block
    %p.label= 'Description: '
    %p.data= @product.description

app/views/products/edit.html.haml
%h1= @product.name
= render partial: '/shared/alert'
= form_for @product, url: products_path, method: :put do |f|
  #{ f.hidden_field :id }
  #{ f.label :name } #{ f.text_field :name }
  #{ f.label :price } #{ f.text_field :price }
  #{ f.label :description } #{ f.text_area :description }
  = f.fields_for :product_attachments do |pa|
    = pa.file_field :photo

  - @product.product_attachments.each do |product_attachment|
    %p= image_tag(product_attachment.photo.url)
    %p= check_box_tag :_destroy
  #{ f.submit }

app/views/products/index.html.haml
%h1 Listing product
= render partial: '/shared/alert'
= render partial: '/shared/table'

app/views/products/new.html.haml
%h1 Add new product
= render partial: '/shared/alert'
= form_for @product, url: products_path, html: { multipart: true } do |f|
  #{ f.label :name } #{ f.text_field :name }
  #{ f.label :price } #{ f.text_field :price }
  #{ f.label :description } #{ f.text_area :description }
  = f.fields_for :product_attachments do |pa|
    = image_tag pa.photo
    = pa.file_field :photo
  #{ f.submit }

app/views/products/search.html.haml
%h1 We've found next product by your criteria
= render partial: '/shared/alert'
= render partial: '/shared/table'

app/views/products/show.html.haml
%h1= @product.name
= render partial: '/shared/alert'
.product-details
  .details-block
    %p.label= 'Photos: '
    %p.data
      - @product.product_attachments.each do |product_attachment|
        = image_tag(product_attachment.photo)
  .details-block
    %p.label= 'Price: '
    %p.data= '$'+@product.price.to_s
  .details-block
    %p.label= 'Description: '
    %p.data= @product.description

app/views/shared/_alert.html.haml
- flash.each do |key, value|
  - if key.to_s.eql? 'success'
    .alert
      .success
        %p= value.to_s
  - elsif key.to_s.eql? 'error'
    .alert
      .error
        %p= value.to_s

app/views/shared/_search.html.haml
.search-form
  =form_tag search_products_path, method: :get do
    = text_field_tag :search_query_string, params[:search_query_string]
    = submit_tag 'Search', name: nil

app/views/shared/_table.html.haml
%table.product
  %tr
    %th Name
    %th Price
    %th Description
    %th Actions
  - @products.each do |product|
    %tr
      %td
        %a{ :href => products_path(id: product.id) }= product.name
      %td= '$' + product.price.to_s
      %td= product.description
      %td
        = link_to 'Edit', edit_products_path(id: product.id)
        = link_to 'Destroy', products_path(id: product.id), method: :delete